owner: mikucat0309
repo: upptime

sites:
  - name: Official Website
    url: https://www.fcu.edu.tw/
  - name: iLearn 2.0
    url: https://ilearn2.fcu.edu.tw/
  - name: MyFCU
    url: https://myfcu.fcu.edu.tw/
  - name: NID OAuth
    url: https://opendata.fcu.edu.tw/
  - name: Online Judge 
    url: https://oj.fcu.edu.tw/

status-website:
  cname: status2.fcu.mikuc.at
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Unofficial FCU Services Status Page"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
